[package]
name = "plume"
version = "0.1.0"
description = "A clean, lightweight PostgreSQL workspace"
authors = ["Plume contributors"]
license = "MIT"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "plume_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
regex = "1"
futures-util = "0.3"
tokio = { version = "1", features = ["io-util", "net", "sync", "time"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = "0.2"
russh = { version = "0.62", default-features = false, features = ["ring", "rsa"] }
rusqlite = { version = "0.39", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
tauri-plugin-dialog = "2"
tempfile = "3"

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3.6", default-features = false, features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.6", default-features = false, features = ["windows-native"] }
